### ISSUE TITLE
Can't access spam queue

### ISSUE THREAD

**Issue by twd3** [silentzco/statamic-akismet#21]
Says I have spam in queues but then I just get a weird checkbox in all queue's...

![2020 10 27-14_40_37](https://user-images.githubusercontent.com/16004958/97359528-80b2df80-1862-11eb-9367-4094bdf023bd.png)

![2020 10 27-14_39_04](https://user-images.githubusercontent.com/16004958/97359535-83153980-1862-11eb-9e09-4912e636014f.png)

**Comment by twd3** [comment]
Maybe I should have cleared the queue's before updating? Or it's missing some css? IDK.

**Comment by twd3** [comment]
Damn, and I just figured out my live forms are not working. This sucks.

**Comment by twd3** [comment]
So I had to disable Akismet because updating broke my forms. I am not willing to test this thing I bought on this live multi-million dollar site anymore. Is there any way you can test before releasing all this stuff?

**Comment by edalzell** [comment]
Can use see if there were any errors in the log Tom?

**Comment by twd3** [comment]
Here's the error as far as I know:
```
[2020-10-27 13:28:15] production.ERROR: Call to a member function shortLocale() on null {"exception":"[object] (Error(code: 0): Call to a member function shortLocale() on null at /home/forge/www.domain.com/vendor/statamic/cms/src/Http/Controllers/FormController.php:49)
[stacktrace]
#0 [internal function]: Statamic\\Http\\Controllers\\FormController->submit()
#1 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#2 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#3 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#4 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()
#5 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()
#6 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#7 /home/forge/www.domain.com/vendor/jimblue/htmlmin/src/Middlewares/CompressHtml.php(29): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#8 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Jimblue\\HtmlMin\\Middlewares\\CompressHtml->handle()
#9 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#11 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#13 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#15 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#17 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#18 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#20 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#22 /home/forge/www.domain.com/vendor/statamic/cms/src/StaticCaching/Middleware/Retrieve.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\StaticCaching\\Middleware\\Retrieve->handle()
#24 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then()
#26 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack()
#27 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute()
#28 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute()
#29 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch()
#30 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#31 /home/forge/www.domain.com/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\CheckMultisite->handle()
#33 /home/forge/www.domain.com/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Statamic\\Http\\Middleware\\PoweredByHeader->handle()
#35 /home/forge/www.domain.com/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(60): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle()
#37 /home/forge/www.domain.com/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#39 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#41 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#43 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#45 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#47 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\\Pipeline\\Pipeline->then()
#49 /home/forge/www.domain.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#50 /home/forge/www.domain.com/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
#51 {main}
"} 
```

**Comment by edalzell** [comment]
Ya saw a few others have that issue recently Tom, that's not an Akismet thing. See here: https://github.com/statamic/cms/issues/2748

**Comment by twd3** [comment]
Doesn't that talk about localhost stuff? This is a live server. Statamic forms are NOT broken. All I know is I enable Akismet on a form and it breaks the form, I disable Akismet and the form works.

**Comment by edalzell** [comment]
That error you referenced has nothing to do w/ Akismet, though. And I can't reproduce the issue on my test site, form submission still works fine.

You said it works locally when you submit a form and have Akismet enabled?

**Comment by twd3** [comment]
Okay, first off sorry Erin (lol). Since you said you can't reproduce this I dug in. And it looks like updating my composer.json and running composer update fixed every issue I was having. Man, this looks awesome! Just for future people below are my old composer and new composer.json...

OLD THAT BREAKS EVERYTHING:
```
    "require": {
        "php": "^7.4",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^1.0",
        "guzzlehttp/guzzle": "^6.3",
        "jimblue/htmlmin": "^1.0",
        "laravel/framework": "^7.0",
        "laravel/tinker": "^2.0",
        "silentz/akismet": "^2.1",
        "statamic/cms": "3.0.*"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.2",
        "facade/ignition": "^2.0",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^4.1",
        "phpunit/phpunit": "^8.5"
    },
```

NEW THAT MAKES EVERYTHING WORK:
```
    "require": {
        "php": "^7.4",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^6.3",
        "jimblue/htmlmin": "^1.0",
        "laravel/framework": "^8.0",
        "laravel/tinker": "^2.0",
        "silentz/akismet": "^2.2",
        "statamic/cms": "3.0.*"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.5",
        "facade/ignition": "^2.3.6",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3"
    },
```
