### ISSUE TITLE
Server Error when accessing spam list for a form

### ISSUE THREAD

**Issue by malle-pietje** [silentzco/statamic-akismet#41]
Using this version Statamic and add-ons:
![image](https://user-images.githubusercontent.com/12016131/226172353-884e6053-4257-4ced-ad40-63e14efa4c50.png)

I'm using the Akismet addon which is working great so far, except for this error that is thrown when I try to access the spam list for a form.

Looking through the spam entries manually (both through the shell and through the web ui using the spam message id) I can see that many of the spam messages contain multi-byte characters.

Any suggestion on where to look for a fix?

Here's the full trace from the laravel.log file:
```
[2023-03-19 11:19:04] production.ERROR: Malformed UTF-8 characters, possibly incorrectly encoded {"userId":"e2bfb2eb-02b0-44ad-9241-34d9b8bb15f9","exception":"[object] (InvalidArgumentException(code: 0): Malformed UTF-8 characters, possibly incorrectly encoded at /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php:91)
[stacktrace]
#0 /home/forge/zzzzzzzzz.net/vendor/symfony/http-foundation/JsonResponse.php(49): Illuminate\\Http\\JsonResponse->setData()
#1 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php(32): Symfony\\Component\\HttpFoundation\\JsonResponse->__construct()
#2 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(101): Illuminate\\Http\\JsonResponse->__construct()
#3 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/PaginatedResourceResponse.php(17): Illuminate\\Routing\\ResponseFactory->json()
#4 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(133): Illuminate\\Http\\Resources\\Json\\PaginatedResourceResponse->toResponse()
#5 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Http/Resources/Json/ResourceCollection.php(113): Illuminate\\Http\\Resources\\Json\\ResourceCollection->preparePaginatedResponse()
#6 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(888): Illuminate\\Http\\Resources\\Json\\ResourceCollection->toResponse()
#7 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(875): Illuminate\\Routing\\Router::toResponse()
#8 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(797): Illuminate\\Routing\\Router->prepareResponse()
#9 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#10 /home/forge/zzzzzzzzz.net/vendor/ddm-studio/cookie-byte/src/Http/Middleware/LicenseMiddleware.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#11 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): DDM\\CookieByte\\Http\\Middleware\\LicenseMiddleware->handle()
#12 /home/forge/zzzzzzzzz.net/vendor/statamic/cms/src/Http/Middleware/DeleteTemporaryFileUploads.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\DeleteTemporaryFileUploads->handle()
#14 /home/forge/zzzzzzzzz.net/vendor/statamic/cms/src/Http/Middleware/CP/CountUsers.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\CountUsers->handle()
#16 /home/forge/zzzzzzzzz.net/vendor/statamic/cms/src/Http/Middleware/CP/BootUtilities.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\BootUtilities->handle()
#18 /home/forge/zzzzzzzzz.net/vendor/statamic/cms/src/Http/Middleware/CP/BootPreferences.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\BootPreferences->handle()
#20 /home/forge/zzzzzzzzz.net/vendor/statamic/cms/src/Http/Middleware/CP/BootPermissions.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\BootPermissions->handle()
#22 /home/forge/zzzzzzzzz.net/vendor/statamic/cms/src/Http/Middleware/CP/Localize.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\Localize->handle()
#24 /home/forge/zzzzzzzzz.net/vendor/statamic/cms/src/Http/Middleware/CP/Authorize.php(25): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\Authorize->handle()
#26 /home/forge/zzzzzzzzz.net/vendor/statamic/cms/src/Http/Middleware/CP/AddToasts.php(22): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\AddToasts->handle()
#28 /home/forge/zzzzzzzzz.net/vendor/statamic/cms/src/Http/Middleware/CP/AuthGuard.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\AuthGuard->handle()
#30 /home/forge/zzzzzzzzz.net/vendor/statamic/cms/src/Http/Middleware/CP/ContactOutpost.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CP\\ContactOutpost->handle()
#32 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#34 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#36 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#38 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#40 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#41 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#43 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#45 /home/forge/zzzzzzzzz.net/vendor/statamic/cms/src/Http/Middleware/SwapExceptionHandler.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\SwapExceptionHandler->handle()
#47 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(797): Illuminate\\Pipeline\\Pipeline->then()
#49 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack()
#50 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\\Routing\\Router->runRoute()
#51 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute()
#52 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(190): Illuminate\\Routing\\Router->dispatch()
#53 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#54 /home/forge/zzzzzzzzz.net/vendor/statamic/cms/src/Http/Middleware/DisableFloc.php(18): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\DisableFloc->handle()
#56 /home/forge/zzzzzzzzz.net/vendor/statamic/cms/src/Http/Middleware/CheckMultisite.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckMultisite->handle()
#58 /home/forge/zzzzzzzzz.net/vendor/statamic/cms/src/Http/Middleware/CheckComposerJsonScripts.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#59 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\CheckComposerJsonScripts->handle()
#60 /home/forge/zzzzzzzzz.net/vendor/statamic/cms/src/Http/Middleware/PoweredByHeader.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#61 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Statamic\\Http\\Middleware\\PoweredByHeader->handle()
#62 /home/forge/zzzzzzzzz.net/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#63 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\DisableBrowserCache->handle()
#64 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#65 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#66 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#67 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#68 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#69 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#70 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#71 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#72 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#73 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#74 /home/forge/zzzzzzzzz.net/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#75 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Fruitcake\\Cors\\HandleCors->handle()
#76 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#77 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#78 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#79 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Pipeline\\Pipeline->then()
#80 /home/forge/zzzzzzzzz.net/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(134): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#81 /home/forge/zzzzzzzzz.net/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#82 {main}
"} 
```

**Comment by malle-pietje** [comment]
Here's an example of a spam message containing multi-byte characters as it's shown through the web interface:
![image](https://user-images.githubusercontent.com/12016131/226177825-e6e2d2a5-7881-4dc4-bae5-bb5a0975eb89.png)

**Comment by edalzell** [comment]
Interesting, can you please share with me one of those spam entries so I can debug this?

**Comment by malle-pietje** [comment]
Sure, I've uploaded a zip file containing the yaml files for all current spam messages here:
https://stack.artofwifi.net/s/C6pGX5myDqBEsg9l

Please let me know when you've downloaded the file, I can them remove it from the source again.

**Comment by malle-pietje** [comment]
Hmm, the strange thing is I can now open the first page, probably because the triggering message has moved to the second page.

The layout of the first page is broken though:
![image](https://user-images.githubusercontent.com/12016131/226303091-9eaa1d7e-2f1e-4ae4-9b3f-1b5ba85bf03c.png)

I'm also unable to change the paging size. This error shows up in the browser console when I try to change it:
![image](https://user-images.githubusercontent.com/12016131/226302731-5483ea65-cfc3-4efe-a0ad-732c22a49c3c.png)

**Comment by malle-pietje** [comment]
One additional note: the paging error also happens in other table views on the cp, so please ignore that part.

**Comment by edalzell** [comment]
> Sure, I've uploaded a zip file containing the yaml files for all current spam messages here: [stack.artofwifi.net/s/C6pGX5myDqBEsg9l](https://stack.artofwifi.net/s/C6pGX5myDqBEsg9l)
> 
> Please let me know when you've downloaded the file, I can them remove it from the source again.

I have downloaded this now, looking into it today

**Comment by edalzell** [comment]
It's not the multi-byte characters, someone has submitted a binary in the `message` field.

It's in `1679073412.4473.yaml` @malle-pietje. If you remove that file everything works fine.

I'm not sure there's anything I could do here as if you move this submission back into the `form` folder you see the same error in the Statamic listing. i.e. if you remove Akismet and submit the same data to your form, you'd see the error in the submission listing in the CP.

**Comment by edalzell** [comment]
Statamic bug: https://github.com/statamic/cms/issues/7775

**Comment by malle-pietje** [comment]
Thanks for the thorough analysis!
